keys:
  - &ad_skadi age1mmqej3arlv2wx96m2gh9fgvqpkwaeselzfu4rqfn54artx058vys7g3ehq
  - &sv_alfheim age128p6n3akchec88ptd6anpcssxzr9t3h4y0xzc6dkcsh6g3h46qmssy76fh
  - &sv_bragi age1exkagk0ztmnw7kvx3wwwqjgx3m2zxycgg46xmrt7pvqlngqgjyeqc4ajqh
  - &sv_gridr age1u0pct8sypn6jtwwnzqgsdy3j7regwwqz5xw8d3mp6sd904xx2d0ql2qhju
  - &sv_hrungnir age1t8499a2tna8pzn448ylnpwach59l6m38s33pzdmy4vhy492nevpqq7l6tc
  - &sv_jotunheimr age1smvmkjl0csqh3wmx9744xqatghnrpnj0y8hmv88gy5llrpujmetqhu9l4g
  - &sv_matrix age1f58klxxdsk02cqrzprvfa4rt4spn7ch5v37thk35j8yzhfglhpgqhsh0n7
  - &sv_muspelheim age1328qtjtudgc3zgg7su05ja20kckx50jehs0v3q3mw6k64j0dzefs752tu2
  - &sv_nidavellir age18qjk9pk7z7lyjkwlkthee3pcywupxs2jxdcczmngdrjwmxgytdnsakwks9
  - &sv_njord age1v2vrn026vtgfkw8v2uez4ljhz44f8j27y5ueacphk8n2lr6q8cjs583tcm
  - &sv_skadi age1dxvqqvhc02fu8vv827wxum8sfhcx326p4trx8keaywv058jlk9kqmfvztf
  - &sv_surtr age1fekpnwvr7xzkfmwx0t3ar3h0e6sdl5jxskupy2hnzc4d08c9mv2qz3ksx7
  - &sv_svartalfheim age1fw6dqxpmkee7785jp7ra97v2uteqmyx9j3ts0zv38t20x7tnvuhqtpelw3
  - &sv_vanaheim age1jnpyg8chayw6l9wfx209hvkddq9cult3qdyuf7trljs6t5vf3czseu8qlm
  - &sv_ymir age1anrdj6swtlq5ll4e369gz3lh6aj2sz6pj5zh25uhltjfk4z86azsfsxk9a
  - &sv_yggdrasil age1yejm0ghvycctg868ag2u0awkf7crpuh59nfvy73dvsuuuns9davsxc6ssz
creation_rules:
  - path_regex: cloud/matrix/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_matrix
  - path_regex: hosts/alfheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_alfheim
  - path_regex: hosts/jotunheimr/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_jotunheimr
  - path_regex: hosts/jotunheimr/guests/gridr/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_gridr
  - path_regex: hosts/jotunheimr/guests/hrungnir/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_hrungnir
  - path_regex: hosts/muspelheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_muspelheim
  - path_regex: hosts/muspelheim/guests/surtr/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_surtr
  - path_regex: hosts/muspelheim/guests/ymir/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_ymir
  - path_regex: hosts/nidavellir/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_nidavellir
  - path_regex: hosts/svartalfheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_skadi
          - *sv_svartalfheim
  - path_regex: hosts/vanaheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_vanaheim
  - path_regex: hosts/vanaheim/guests/bragi/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_bragi
  - path_regex: hosts/vanaheim/guests/njord/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_njord
  - path_regex: hosts/vanaheim/guests/skadi/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_skadi
  - path_regex: hosts/yggdrasil/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_yggdrasil
