keys:
  - &ad_skadi age1mmqej3arlv2wx96m2gh9fgvqpkwaeselzfu4rqfn54artx058vys7g3ehq
  - &sv_alfheim age128p6n3akchec88ptd6anpcssxzr9t3h4y0xzc6dkcsh6g3h46qmssy76fh
  - &sv_bragi age1exkagk0ztmnw7kvx3wwwqjgx3m2zxycgg46xmrt7pvqlngqgjyeqc4ajqh
  - &sv_jotunheimr age1smvmkjl0csqh3wmx9744xqatghnrpnj0y8hmv88gy5llrpujmetqhu9l4g
  - &sv_matrix age1f58klxxdsk02cqrzprvfa4rt4spn7ch5v37thk35j8yzhfglhpgqhsh0n7
  - &sv_muspelheim age1lx8zxzgumkxevzp0cy0ndvdrvpk94qfvxrdfd86vuydecf586urqhwc52e
  - &sv_njord age1v2vrn026vtgfkw8v2uez4ljhz44f8j27y5ueacphk8n2lr6q8cjs583tcm
  - &sv_skadi age1dxvqqvhc02fu8vv827wxum8sfhcx326p4trx8keaywv058jlk9kqmfvztf
  - &sv_surtr age13w6jhmkzfj6c5p9v7s0ld2trkewypjhcjq9yejgkps7wlyk2eu3su8jf5g
  - &sv_svartalfheim age1fw6dqxpmkee7785jp7ra97v2uteqmyx9j3ts0zv38t20x7tnvuhqtpelw3
  - &sv_vanaheim age1jnpyg8chayw6l9wfx209hvkddq9cult3qdyuf7trljs6t5vf3czseu8qlm
  - &sv_ymir age1x9p402sjg3u6y0ln08m2ujq2smr4xdgv7h32sn468ctj9rgksslqyn30ce
  - &sv_yggdrasil age1yejm0ghvycctg868ag2u0awkf7crpuh59nfvy73dvsuuuns9davsxc6ssz
creation_rules:
  - path_regex: cloud/matrix/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_matrix
  - path_regex: hosts/alfheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_alfheim
  - path_regex: hosts/jotunheimr/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_jotunheimr
  - path_regex: hosts/muspelheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_muspelheim
  - path_regex: hosts/muspelheim/guests/surtr/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_surtr
  - path_regex: hosts/muspelheim/guests/ymir/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_ymir
  - path_regex: hosts/svartalfheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_skadi
          - *sv_svartalfheim
  - path_regex: hosts/vanaheim/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_vanaheim
  - path_regex: hosts/vanaheim/guests/bragi/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_bragi
  - path_regex: hosts/vanaheim/guests/njord/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_njord
  - path_regex: hosts/vanaheim/guests/skadi/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_skadi
  - path_regex: hosts/yggdrasil/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *ad_skadi
        - *sv_yggdrasil
