keys:
  - &ad_denai age1mmqej3arlv2wx96m2gh9fgvqpkwaeselzfu4rqfn54artx058vys7g3ehq
  - &admin age1pq1yvcyfafmj6uzcr5g2f2dyau897g9x4cvndfzjvv9xx23jesrtnc5nghmknwcfvz2hjksm7rjuafjncv43qzsjefqhnz4v0q9mumqvl2xdwcnw0l5sq80f5a38vqczzwkcej3jhd3fyntc63nkf38taakk74upyggw3qpptyw2evs0yak2y7av4t8q4asfhpmyers6le8cse824alljplg3epkvdcz5wj3l5qfnt0s68wkq56p3dhcg9637tp5mh75rp2a5cge3zn9t5337cgv4jykc8uehpwskw8e405ssqdtpfkx5806v5skq5nx8sj5duhvzclf2l8wajj8ljm7zqq97f2sgrqcvzxxj9x04a65wd5hh23w62r3d7f555u3laz0f2h24ssye25r95w0pgjgjess5v4xrk7sghwcu27sn9awmyrasdhge3gzlfhaqw9gqx05wkrwxcpgeqtqpg0cjzue92pmdfeavz9psya3raypnynz0qep8xvzqwekgy9h8v2f2s9zv3hf8nzcke2xwmmzpxxjgnnz498yrps268ny4m328enhql09xgwecjcwujkdraypzxwj5pt2xdttmvxtuhvcdwqqyez9zejhxq586cpkuzyky8r90wkszfej0rm37a2esc5hk9ysp0dnyhwpfvnvjrgvl3sdv47xfkz7wyrmksfld64ejhncpkeeqkg0x5jqmraqnfx5f5g82utgwv3sxpye3jcdefm0q7m0gl5jy28np0htxe5nkzmefmjzruacq5ydfgrufdyd0ec4nf40q27hjkxcg9jrdx2e4yzdw4y3vxrqzqpctrxsqccpy2mqqrszwr4k295rje9jdqlnrxpfm4m52pq5js5wdr3hj78e4fnasezyjgp5lnfkz5j3gafptgs7fatn5vjdtzjxuxju7y5uyuszdxzsgw9zsjkvmztk64czhacjna9cj8ht08r9df8ay6h88k9nwq5qt0gvp78scnyw6rg3zv3l445wwf22zjunxk6uy27scutvj9kz6yjegq2dy829kgud448m2r88vvdptg3kppmjjzjhyggev5ptsq2rtvguermqq2454du4knteur3xam0zrpdacjjz79hr8cz426egrzvkj94jhqz68af480rjgky25vq9xfxvg3vwt4qnzhn3cmkkvucp2u9csmu0zxphn6rkhl450prkp36zzruhxd38fcs0ml4ed0c5cemjy7txf78kfsv2cwdddcdf3jrg753xlqyk9ajrlf48xnwndt54yugll6hs3gsyknch0q4y4telajrdhmvwd2gjevhv0nkzefukhqgp5zkp2krqdzfe28px0zqw3ejljan6vyfxxaax6hrpvp4gfr4d5tzwt2q0j4rcekl6g67sd3emdmfrj2rwldv5q6krdywrey5vt5cgtyq0r9hr0mzedz5ky5rd82gudt63x7ax7ay2xfpxz3gnryfttm5xl0nkjcs7vfx0u5ungexksujgggx9j0vt9lh95s0te3p2842894jxu7yspchsfzx7gfc2s0jftqad0g0fzudcqpddy5etj2u243d5ea4xcrnfw4h08dfql2r8w0zexprzaz2qztjgp2cjenjtckekkvpvfl906p0c9nuteyhza7nzutp6wphrryc8n3t0f5cen2w49sy2kjm3m9rp25xmw5327paqtk5er88kcf598p2zmmrwu0m4dxfs5vechzrk7g83cdxpgge8pwvgjplparukwyge40f0u6h40dzzgtytktgx7gqefr5dpad99xrjhxvq9a7lguettdusr8urx0c9sxjwjdfzv57hu59wfp6gkn3p5pwan2qurls0uuszu48yeuqkr2qvv4rxfy505gpgxamwapxy650z5c3uem3flvjk09ph4t4qe0d3jcrpg03csjk

  # Note: age1ffxsuhgqnx0ztxm7jghnn5pjzv5j2d6atcm8v40xh573gv0pc90qlpllnc is used a placeholder key

  # thebeyond
  - &sv_thebeyond age1pq1mdpp4m2sd9v62sc732d07pypaucmp5k6rj78jsssfw6947zhqng6umj4knryzyjm55f8vsnf3kpp0ggsf57ls8kpgj3sjfyscgavats8ewhmpqudxz84f8ptk7yz072s4pwzy4xyuycryva3ysghs7cz08yk9xkwv7dpgg2lu6nntw7szatkv3rwhzxwet9jzy3eh7kseaxrdqfyvux72p9tkqjetx4jg8mx02dek7a5233svxc5gkkgn38rt2zc22wy9q9ku9rr77jf3lllft729z63vfnskqe6zrlrzrzcrd4vxpj30spnuntmgpw4rst9nj9kkr9f6tq6awwp4d8qdz3vxz2zc400d3d0mhv8usnqhp0xxvxg26tjdg5u5ymmt92kg0znzhcupq8pcgfgjt6h66gnfvhl89qnuw27rdesg5dceg73w4ups8mnvy3qtgdg5655t92jhkwvwp4vdjxenda5yp3kqt5u8af35gj8ucevcw6xduvp5teft7pyed9lrvk9q7yuplmfpsp2rfrwj9acjds5f557e2am2ulswg5dqlc85zn7395vkxqmk06q4e72v4353vhttcpfe8zkwgamrf33xq243vu5jwyu49wqk5kjqs3wvggcsps48smfjn6jcr8xnq8vvkhwpzajnzm4wquqfe5rrskxpvl23pcc2qz5d4zpkwhtg5vzezdpp9wu4zwq8vdz8dlr9t6y0ncl0s3qldvjfw280ezm577hsa4uhjfah2ascrrn9cvz3a3rfzd4d24kh6pksrcy34crdsfw0nj6pvkqjuus76sygsajgjq7et3z5yd0vujj076sj30fswt9cdlypwd67h99c0t9mt7q36870d0mk6uhqkcvm0sqx3z40sfwvyv3s5xen3w06l5q9pmxxjh5qlg62ksgdf938tgqky8zzuxyjffvv7v20f6009ygraj3p6p25t5wn9nu4v2jtxnyajp90yfc8p5gznxc6anyvvm4d9zt2y783xlmnwl4kh97g0etsmzhn5ugzj23mqsrhwvnum98cf72efw7zfvyzajawd44hqf8khjkelwu9vj6q5nfkcqlclcqv0hkpaefvhycjc66wvz5qqg88u9jcpkzd3wnxa2u24uz0ag8vkztnvpkhthpufz0cwug5xn9czstch34jl6had94nyucffvm7jl6gus05efm5f75gd5n98vhgzgtc779hf7yzxeuze3xa8fvmx6przcqzqdx0gtqly3kltgjfxhxhupcpxpnyk2dvxulgtyssa3u8cxxzwzrjez4gjyyquenc9zpr2sps6qrrqz437dz0lehmm242y2hwqsau8q3swy57fz2609rqaxd0fa9yevvp92hlce69fd9fcdzppu84qc7wcvujfptdc7zcrzmzypu6f9x2uvz8kq5qft8n6ez4pahn2v4ms5muddyk96k2f0l5f0lg4n40kqf0y5vnvvqv7wk8xk3yhxh295yfmsmg3p4337jy92ac5cmex5mdk56ctzy2jzjqlnjlqf0hjcmrw535qhgyrfczkvew8zhj6wzglsv5kfkncp88rqqcsalpyd2m0nqwh6cy8xd93da3s29gqusphsfu3d3j7syrw9ucxl54ufdyrf23nn9deme9xacsvp6g9pmpxeze44scrnmrtve0dlvt96r0tjfmf4y08nrx8kujstdg5dlgm4gn6tn0kd9kj77hdc2u7derxzfq65ejpjtnjpvwd4gqkyz66cyyej8ysjgkhyk2q085j3qs0zj70dmvcyy9dchw7ndwg9pekucvexjsgxx48qzrx4zztsj3ks2h0vgg0vquyy0t6axud02a0f260ukvm5pka5ly8gurz434pkrtguyajq40htm0uzjzta2gjs7ufwv3dyvk6svj39dh4768ugcxn8k
  - &sv_phantasma age1pq1s2mcrzhcc46kjl5e8fzkp3q430sn5qc3s3xasnww5282n3tz6lg28mk2jkz9zgwunza40537hekggjzekczhyw6wf9lkxecafygt5qmmw8j79twuq63xdzzcq3dhnue5cgdyqdq9jlpclcshsfsc2tu43wm45e6y3zndg2s0a2dcx0mme9v9nqnhe38ege4p2edr99vywpfxz37kc7zzf2j5l56vmnrhx9vfvc92fjfwhl9ptmdmamexnnzzt3pu2klerpvznuvt6u5ts7hzkcweldzt07jexv6enawqsyf8kpzfrxnmp3t7za4z5nzzteztntej9y5t4e3536zpmaercercjkz5rxzhu89ddwvtyngtfzwezw8cd9r8g2gufp2uaz96hw6mql9l4xxzudydxcqm3a3yfl5dzcs6dqwatppz58nuy4hjfrg5ym572cma8wacg3d38vcztkrg2ps0gp2v3fvnsupkpx32seq2va6vs2kv8wafqdju03ejtee529gkewn3eks4lp6j69dewuwvndujcjyf27nkpmwpthuy4337kqdr5x057ac3gg4elxgmzfxexeh9ewjp3kq6m7cqqdjmzqr34wszjz4hprp4rt78xhryghnu8f04usmex2p2j0js8jqxks47fy97689u7qee73w9s283x4us9gaqxqg86cym0quev0n23s4ux9sv2g5xu5cnx64mp6ytpkj5hvjpgsle735rd76y2wgky48dwnc3jswesdmrv5cpgnhtyulvj3aa7hpux57yft4r0zf304254jd3wzmg9euxc3s870lpst6lts7jfyuz3frllk4x5hmtx64pstj87ef03qqrr4zxs8dz0lajftqx7gxte62wt6a2w8jewgp74gkylnx6rs3ykxe5qj8cd5xvkcvtqat4rgmdx7j2pcvxzef5zvs380zz6n9wuqafdtxc0875pnvlqdtkkzzqaj5kl3w2tt66h3kmk2fsm9a6l7m8w5ljqs48hnuu38rcwst0t0564rmmhkyhytwncyms72zgzmqm5jqmfahcjrqklguxpgfgh7k2m5lkvqcjxy57sq52wygr53an0s2cg06xtj3ge09gf3f6yxamxe6m3zkws34t8drm03zgxf5k3rgej6sddw6ujqtxuxv5lpahyzqsqscqcjaeu70cqz4htdufxd6382m4tx4t6dg26styxprtw27fwagqnr333ddy3e5gja5tl7g5v7a3yxtfxhzthzghp7zp7ugtw7r7xfh22csw92nsr5fxdzlsfd7axt0qr9259up5elcxjd7exl6q9qhpyvkhla2luzwzg9se5sgpf8s53sctyfpzpjz8w5yu3wm5p0hmnqx50c7d8znv4ldxv4k425tf397ae7an6f2g6l0g23tuw0ds5s24ygt7xmuj87v8fdz4cymdhx2h3gpaj563vyuxq8q8qhr85ummrckzlm6z38r5yruutfmnvj4j6wwdlrqnz6fngu8jed85vg92ugxy7243gurrqy3zcaz4rxe7n2nn7vpt7ux903yt24m3esdtrpk2d6ngwfjhw52xnqj5tgcqef9t4vjnsppjttyd4xhnnvtlkxjwz2egyctpqkvwj0e47puw0s2ynaypxytspprt0rc0hj0h3z3999kxa88uekemqevnxty2jsehk0mqyg9htl0thj7l0s3few5n8caz5vyptkqzrwmtq0yahuxt9xf3kwjqsk58yw4rgm9g7qjslkysekjk9yqmczm859cx5epuctc2k0hyhvhpwquxcqa369tyujfcjup5cyf39340y9dre7d07g7za56yuljel48uf9phqgxpcznntn6umj5a2zssgwjswxer6ce4ft2f859cs3fxa4hzl8elrxxxseurhq3zdsees29rzm6n9qgmchcg

  # liberl (reusing remiferia keys)
  - &sv_liberl age18e698z5sf5twkc8vup4edc7nkaza2nquuzqja8lrv7r34mzx84js48jps0
  - &sv_bose age16hu3zrv7ncxl4f3tcddeptcqj3azjrj44gamwtakgl9yp723092sgcakqk
  - &sv_ravennue age1ga0jsf9s429z7m65rem045c3m5qaqa33xvuqlgznkzvfsdx6e9gs0vwf5s
  - &sv_zeiss age1dvk7gqyw4zwnnu6u3dwke94unlkw85kmlw6s5lfq59jw32s5zdks4c32ff

  # erebonia
  - &sv_erebonia age1pq1tgfrvlz6nfej3dt39dl2z5fxkmyc5eqrdgkye2ryxaenys2me65m6jxjhgzw2k453qvt2snpteqgga3r98q8xt2kcwzqugdx435skrnsqwvnq7cvhq9r36ca3u58hmtqzsgf8z3z7vk8pvykmagg4cd40de789dr68qjfue77rsnc7cr38s8gaajvu78szqtua52ppyzx6p5zqfyxf2tjfudhv9tgwsgxt494sktkd433rxffq3gv5yf8nstvz8aashkp7uu0p52d7pc92vwy80fsgkccg7d999nachq0vdks0pphsyl75y8huv8epq64gxsh22pshy9pwscza7fwacnpuynfp6t22g5gapc0hn2637evz5rd0n8276xjhrs0y5sh7yc992tc4z9gf3kzvqzlw49vurqpjekchefk4azxd3k7z2xjn05kk82h3z8edym8judwy2zqz2pg4790sg5j6lh6azkwh7r2qzaxrrczdy5djlm7kmcdzqj5vc8kw6e57s8ag5quqezujkft86rzed6204umd8j8tqzs4tyjs0s2qn0vyx8cr8jxjcss7myrpkxwqurk7s8gfgstvd5c7zthwgcjl573vpvmgtmvxwq96wq9wljnfe2zz4jjpdx872nppj4tvnyqwgmc77krdegggrrelt5l9tqksjgyxzmvdmck8rnnr78jn06ppqvznsd52vftju39dm34pvf0rd2jv4apg43gf362f2m3d5mq3eyscd2nf7m67maspt88nzz260eyeu2zjy4m42nwkk9cjuyp4vxwq8p0ds3mjc479pxmh9ex9jmv06mkphxv9cdqs366rc9ewkuegr0gfa2fyjmtj3grw9peqassw9qtjg7954mhgxyy665gaqkezkhgghqpu67k3v2tlz4yj86jum472jdvzs4u4gugd5vh7l3segcuw6pvtqhzgk93v3gzvxjjfvadfswqedd2arsk2cz4x5h3ftucv74uz5s60dpgvf297fgqfg26fkzf25qqff9h5jfqrmppqmtv73r8k5p62nm4em5r78pzcmnfx4vc7n095ahlthz0vpr5nnr2ergm9q5htmydsx2rkv4vkpq0fpfmu470g9y2jdsy9muwpx9axuqh799x9w27ryxjsdk0qhexy0n4wuu0y2eval505sst3jxtvvyy39xf8jn90lcvnjkdgfuyd9a8xx8c7acqtu28sjn2efuw3t88jfwt4pfmq8q3j6xww3cdsx4kpmtyt2nzgycnrxphj7ncv37xj2hpjtfjpxkvqgn5erunz9lxfmc7dukpnqh0r7pr32vzavgnkzdejwfwa86twe7sh0xrgl3h6z5j72836ay2dufs70jqw2t2jeyhg32qfv6jq0fp2gwl24tqqr6qmz8z7pvdmuryjra6434n95hv5c3s65n9z40zye49wa9huuvastmqmwhe9fwh8263g75ypq03mt2hvsnwudnpylzg5v55u9zpqryjwgh88uus5mjaw826p7sp4juyqkcp9vfcpwc2jydg3sh9l9y6xq5nxqpkj386e5jrangdx5y9fukdq2jwxs8tz0j5f56qrffs48k3prl4y578slmxn9l30d6mlvphjtaghh5anpavcrwn66h888stammd3gnasf696mf79260gxrfhd4pwhf774wsjx82ryf2q28zj5dw5jm6ajjt4mqrgvfn5ygjgxawy9hseqlgss8204f03znevakr0ddj286x8rtqy6ydfzvjf5yx366gqv6p7nyftpswsquja822ht3kk335wvufn2swmd885lcqfnslgzfsjmesv564wk2mthlk0zuljsl455ut89zxug9qj5ypyzj7rt4zf0xjavzmquwchsnr93equceccv4kjpd3s26yuegdg6hcry3te4ttu55w0fh
  - &sv_roer age1pq1kdur40a4qpyz4j89pz2ftyycc8pg0q78we8s5qv9ksjrnc9yv3nme2yqzvw339aa56sgrzn7ry3z94xyrsx6z5cylfmz3gsd5xdmvtwusldfr2pfry946a33h7jeswdrt08n5y8dx3gmy6nfjma9f9cufztvgqv827c0jsf0permq76ytqu0gwh6vpeltlqcn0xpj96mnvs4wukwqz79yzg5sh5xkhkpya2zy5rw0j2j35uckks4axr3wah857zwcn8p0gexdejyu85rjcl3kmgtxe0v6wf684vkzdavnf5xffz4h9xxl7unk65tlhrfjfae5a3pyysqmseu556nxl8uyxx999es647sfyujdsxxwsjmrkasjwws3szkv5uevt4fjj7ugz68rvg8vphd85au7848p92pr7t0xdke2mralajeq9t35x7m3uurn22pstp0qeg3mve4xejfjmcpwqs94dxcn9jph3trar3th9sc2nme647a5d4xqwy42gfm8plm5s4lvsqlm4fjl8qpxyz9hcyqrthyn3zhp939pyt2efx4ynxmk00da2gqgxpkncfq755ueahssl7tzeky9ug69muvyx7jrlnjh098txg078x2egjxgek3xxglk46z662w27e6ytztj0zvwh2zv83udv9jgw2p0jy3acx9cntsx7afp3thy3nzpvnmlna6z220vumj75dc7jzea2s6c8uzwe06edk9zjcgzgr2rsve2jryhe0s806lrdysulquu6rfltfvwqhwffxh6av8jctq9tff3ekukhy0qcmyj4e7v225utrnfh5jfmm32xnxsa0kn3jkt9569vtcx8saqw2z0gnw96a4gs3fmn24zskuexpvs6zsmz6s9ypga8u452fscsjnzdsx9q3gltgj8tlzc3puh9fkcpwzhcpkc4egw5asnp6pscaveyeh36z59ueg3m3sk5cv2z52px9ze7ufzkvgxe54f78qdp87jzxurzdpt7fsvmuqxs9ep3k2dw78zaurqyrqzr3upgvgzqqy3d2aq9f4ksmj97pyesy3tx2arpuqp4q8cvgqhdpn0l7uj983e332wugv8y2zk6ftdatpdq4wnwc8cjqvt599wp2te2lyvt8kggxuu4ztcuyu3arpf0cuyj7qds4g43j5lccqe8c50wpd3ynqjq39lwaaqyjsg075dz8hjktlzwkepatvm9yj2lppvkczj38hepwp546j7zkyafpndcamx4qt4ynjzzuhq0zpr57g3nrfrvtrapsta2p7wv3ka0hgjq3swlz22zqt0zpnytjt3dj3yc5unjymwkmfqkvcxvvyldueekcgs8hcew0lpgans0s6ukzhwutx8vwl7t95lyd3gvjrmqe82yvpwdlwz46936s3v9f6zlgmf2haxsepdwnclvemy9y69kgzk4ttse6229fprfzvq55xfhczkcs6cv9u0973ux2rv7vyf3k20p52yr8wvl90mqajulm2p9r9rh2z2u3xr3ahddrdf2uvqpa32rkuf9ynccttmgudepe8sk95006ws8cyvp0hu7rea4u9t7uvv7q5qc5djfwsyu27lts43g7v0k9lkr7qk77894gjxpt8l23gzpkx2rh0zufauwvejdvujsjgpn22cczgegtrjdnld7f4a3t8yv9c3r7ec4cq3yd2f836wxa3p5wkv5dtnrylykvs3q9mermsz7mfwk5tmslnc7c5lcfslyyn0lpgftmqyv9ln3nmzfcefpaycvmsd009hvnekywy2wnjryprdn2jzwu8mxx2dgmtu89mftczpwzeg4rfhg55dqjfsuvmalm44z3jg36uswpa334hxnxy9v542hgx6w08veq2jux6aym2mzpv47mekw9j9fwqsyue34wwu8rf9fudk4e789gfutz0gqnyxcam
  - &sv_saint-arkh age1pq1e3nj7684r9qg5kztgu74352tvhcv9f9cce02fsthcxhyqauwy8g3ljappqg5qsjgmdmc2yesgc54ax9k5nrecz7v5zj5t7784zuksvekreaygzf7cs94wxp3qyvu08mc4yngvf5526au297q8azqgxv6ydvh0yhsryxmszgj6zyfjwtf2ghnk342mx5grda7nk5er9322w3q29hp8s53k6d38dc5uz0mxz0gq3fkqz500c65p2jtrj88tvmrhtmtc245ke3gteyv3wtpt60ckkktj6fhnuc49qmx59nj24x7kr3ldz0udlzyhh7rkx5gte3l9g08xjt50da6xgp6n2pvyuw5y2t3pwcltded3dsepsqgvpj3pqm84jay8evmfysr7dd3q6gxjqmqc9dfcw93fcv8s7j59tfwxfya72k7j5sccgxqu5pezcmcgkpnjq702kd6q4gez2crezwfeyk5cwqdgxugfhrfna6cpvc5229jgphkurpks4wt7pl93nwp4yevwz0rx3cg9yfm4t9r09e4506rkzl0wf28aeskg9h8hd49pt2tmfu5r7q4dv6r6nfyxcvhkappw97ut2es0wrsh83s92a7gqs2ywfzmgf9v9ft7f76rumdqgrxyuqrdwgn833gjkxnewpfz83024t90aptjm9yquhx8vyf0ndk0zjemc5rpp344k8qgkdy4wsvku3sjgmxp6yj07skrzsqwdp2sk08sdrzq6eyme9vdanvkdvsnj636vj7p79plu26qrhqnslk4xfc0hxz3v79luvyrdm98rr4ws8hsff6etz27jgz5crr0nlfx3scdlxpp023m06svlf6ey876s0cg7zch0fssml6vumns83lgx9kdtqwq9sk6nqer8n4q9d9j7228wyg3wf4rf0uwumtzcl25p5wycul5n25e2n5p956kkmm24ur8e9m5hqh8hmjpz93yh94dya4vgg7e42p4pfyxxjp5693cek3mydx8lq2z69nnr8fjh0uucsgajjm09vyv9lqsreeczrsjclskqclq3vtgdqne8z4py5qv8xwgce8yz4k0kckca9pg5uxkgkcek4xk8qkwlqrh38lczhmnf7j5nyt0t9cn8rex53f0jlm63pp2q35zwj5csqqrhe3vpl9zjtfarymn5jp4fx3vz4ryp0kfxrsydtpzk789dkty6lc8wy82z838dm636359xkv4eu45x0l2zm46v206qeglh3mqsgqs2t0kgr3tajknhqv0evfvj83tq7jqz3747pfsmkfcmuvvmflx7mwfz9f752vyprsy903t38gy6m723kex36nezzsq4mfygn0pwr6rftqmkfq2hvuf33rsjf3ks4kkaarkfufzzrvptsfz2v490fz2kefqwfcz8peyuugx4kaq28ua96lve9s99nm3w869gnfhnvsd9l347dqeqxqk3us997y9r0kqsnsd49jej2vw6xje2umq2d58pe0v29wzvkfqgay0hgq9t2smnxd825999rzezg8klzp80v3w2kwaus67kvelygmjjytzvel2rqmcedkhmzvu093ev9vyw8r9dq47c6kc4ty6kvqvfvlse4e03zztq7yvd4x20r859vy3zgqw9tge8ykzfgf4j9pq2lq9zgzc7j9gadlzh6ctfcuj06csvass25p4yky93u27qj9e2v58qfzhd6grwjlkrup6vrvvggv2xahu45hjvc4j52q0rgswdwp0fez5x8v3e970zqev056vyses8zqwl9qw9g6cyep34cyx5nv30pqywv52kst5n569ua3jtlhfg5clv7rcthdsq4x8qpjq2py3lxgwspuwf8zzqynutzcu08twe8uxrm5wxdxae72f2d25dd7zqq3mqrvywmsc5k0fwqk9vt5w0ecng6ts997dgmx82ax
  - &sv_trista age1pq1yx2sxdjpw6hhg6vsxg7dav65qe5mjhrpzxhunf44exze54dcrl72nz4un0dj3xcxvgmckezl2eah4nf23agcx7kwf0pyfmp8uj44f87kkj4ryptdjc8y0y9wkh9ycp8z4y5l20575ktkxqzyy2v36tvyp20hftpspg3wyde09knr4dph9lhns2fgn3hh05gcgxpg6je63as2c9mmnv5uka56pyfq0jehxxewvx3ncq70w9ede3jf2hscc288vjt52k3fq77f2vvrschetmrcr9zagq60l2s3zsppy2c3xkeud3ttpj5yse24cw33a9yzhwrlknnqr9vtvuxd6wc55kcvcq74kczcu37zuaylwe7vgh3thnkq9fkn7e9xn4clv8qmysggzrqp2s8hdsdnn6c63td5use8gdht48a28fkdj2xtsc438m7ed2s0xx2hs2kymprsk5xg605ukp62j6r97y2td0rvl94gnvj9yzy0zzar746z9q22xadhk7gv2lgmfnwc3y20w7efau4vhzwrt9vrzhchvqj5veecg9tgkjdt9jf4zleazxkej26zrs3gsvm45khf30cy5kmfqfj7nh4fnux6n6szxsywnd8wparj624kx7stxd5ehjldezvxhdzh52yckwfhcex6vsklltrpj34hu8a8qttvczcejamyq28f3j22qqw9y2uyf99yj90t5f638w5ufysk2yepx5yyjkfhv6587v2kyjfjadm5sqju43w8k63unjul4ectdlmpx2a9vnm7sulnmzz4u0u42n32vt5kqjeagq7ev5gp9zwz05t9cl7ydrv4cq4uvyn0ghmnk5pgkeejjqk7uwu8nurdqlyfwhu2dhd0qvqq3yl246yx6gqtmnnkn5kmsgpdtdhlsmzwcugplsm6nj54zfy0u9qa85akjsdull7f5gg4sdy02s78u7dy5nzjlde8x78etjm9qqggf992xyxfk6th9504sfedza9vsuzmnc6cxw9fg04evu0u5uj7n2fhlvnh3k44fxfy53g9jxdhamzhdqnmyz243hdmfjyvvkjhwzmu235q2n9yjw4v9r78z7e4497q6lszrcjxnm9mx7c3vqe8zr9vreyvy9rhzfzxj0yh62zd9f22p39fqrcheq2wvpaqade943maeefylfkmqf7p3g5zh99dnepsllnsmhapya6tjafku7d9gu9x2rc8k6szxwfg3p8cq4zjsx3qmqjfhq7yf7jfyevu9yvq4npsclx8eqss0jeafsplmqksxxpa29stz4q9ddestqwrzghwwj9cg5mmh4jrs3shgzfg8wehpg57qeczurugf3g6ctvuxuxatj22g8v6syuv5yddg79zey8w6jnfzqy2rhhv38ll0th6f2kltp20ta9x276m3aw75mtqrv7qj5yasqvty905p2zpd2ey7xct6ank72nnfpxe3crw3s9cmnx0ewq7q92xx60yxlwg8qp60wsp5tplt5rm9p0kd23pxffuhf8hevt92wd5ljd883t6qs2ut0qyc2twz9a27ywqk3d5xd3qww08m6snwukf0wukkkfakw2vn2n3mxn5gcrh44hxzsw7wauk6eersfs08nzmxtt4cj989wrx3jl5wsd6my7f2fdzw9ufg59spn9ffwy3k8fhxtsremt2kpdwcyqnj6nz5taykcdzxea9hpaadz6t0cqgzr5u28s6qz4a2sykrsfxvumryctnuyvgjpem27nx4y8xxcp34ept8hqjjm4508lemydtdc5ugqpvng7gguewd3pv2gt9usyek6zuctecvx0ldxjuh3pp5xeceatdwtd2ka58uv0ua879ydeqy9mgn8h3q72nkaknnmfeudzcx6khj6epqsswahegqml49yt0y9lcm0kgnstpupggpth2e48axv5s7kk2

  # calvard
  - &sv_calvard age1x6tk8zejwvd8c4nm5jxhh29fw5u5wrd93dhy9qm3hv0pryxad3aq6ykn7r
  - &sv_edith age17n3kvx02g4gwa35spalc3hxm7dlfrms23h53knmeqph6kxfy6c0qmmakn5
  - &sv_messeldam age12ne0n0vt0zf2s7utsn2tfyl6tthc85wuyaqx8x3ua8rwpaelnvnqfnlejh
  - &sv_basel age1pufrndmd7g8sm5590mmrkkqj4x958xnw8ehxu0zlrxktd3kxhy6qxzgkvg
  - &sv_langport age13pysrruclacn7xxhgqhugu5y035z4ntv5ezpkfvrjmuyduy6fpwsj4grj8
  - &sv_tharbad age1cqh7akewh0qn724jjht3nveg63nu5cdu7dsn0nqrut8auyxyrqus387vkx
  - &sv_oracion age1r2f3qnzdlnu28kgg2zwzk44zm2qhjtq98x8l4vsrcdqtl845zsasp6shyj
  - &sv_creil age1zjslnd63kf2k000ahqxqudwmlrluszdg45dczlrxk50zjcujrc9qvwrq7g

  # arcus
  - &sv_arcus age1rc3vtysrzhjrd27evwzraanasxmg2z937h9epyhqmaegay5h3p8qcn4a76

  # users
  - &us_edith age1l9m5wxvev2w74u7hv4ayzc0e300686sagpcmsfr42mr258e5lsssv56tcw

creation_rules:
  # thebeyond
  - path_regex: hosts/thebeyond/microvm/guests/phantasma/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *sv_phantasma
  - path_regex: hosts/thebeyond/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *sv_thebeyond

  # liberl
  - path_regex: hosts/liberl/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_liberl
  - path_regex: hosts/liberl/microvm/guests/bose/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_bose
  - path_regex: hosts/liberl/microvm/guests/ravennue/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_ravennue
  - path_regex: hosts/liberl/microvm/guests/zeiss/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_zeiss

  # erebonia
  - path_regex: hosts/erebonia/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *sv_erebonia
  - path_regex: hosts/erebonia/microvm/guests/roer/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *sv_roer
  - path_regex: hosts/erebonia/microvm/guests/saint-arkh/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *sv_saint-arkh
  - path_regex: hosts/erebonia/incus/guests/trista/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *sv_trista

  # calvard
  - path_regex: hosts/calvard/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_calvard
  - path_regex: hosts/calvard/microvm/guests/messeldam/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_messeldam
  - path_regex: hosts/calvard/microvm/guests/basel/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_basel
  - path_regex: hosts/calvard/microvm/guests/langport/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_langport
  - path_regex: hosts/calvard/microvm/guests/tharbad/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_tharbad
  - path_regex: hosts/calvard/microvm/guests/creil/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_creil
  - path_regex: hosts/calvard/incus/guests/edith/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_edith

  # arcus
  - path_regex: hosts/arcus/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
          - *sv_arcus

  # OpenWrt
  - path_regex: hosts/openwrt/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *ad_denai
        # OpenWrt devices don't need keys - secrets are pushed via SSH at deploy time

  # Users
  - path_regex: home/hosts/edith/secrets.yaml
    key_groups:
      - age:
          - *ad_denai
          - *us_edith
