[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "parse-uci"
version = "0.1.0"
requires-python = ">=3.11"
license = {text = "MIT License"}

[project.scripts]
parse-uci = "parse_uci:main"
